# fly.toml app configuration file generated for turners-of-bytham on 2024-10-30T11:46:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turners-of-bytham'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.23.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
